name: 'Deploy into EC2'
description: 'Packages the lambda and pushes the zip to S3'

inputs:
  EC2_HOST:
    required: true
  SSH_PRIVATE_KEY:
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: 'Install dependencies'
      uses: ./.github/actions/dependencies
      with:
        node-version: '18.x'

    - name: Create App Directory on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.EC2_HOST }}
        username: ubuntu
        key: ${{ inputs.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p /home/ubuntu/app
          
    # - name: Deploy to EC2
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ inputs.EC2_HOST }}
    #     username: ubuntu
    #     key: ${{ inputs.SSH_PRIVATE_KEY }}
    #     source: "."  # Change this if your application files are in a different directory
    #     target: "/home/ubuntu/app"  # Change this to the destination directory on your EC2 instance
    #     overwrite: true

    # - name: SSH into EC2 and Restart Application
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ inputs.EC2_HOST }}
    #     username: ubuntu
    #     key: ${{ inputs.SSH_PRIVATE_KEY }}
    #     script: |
    #       cd /home/ubuntu/app
    #       pm2 restart index.js 


 